# Generated by Django 4.2.4 on 2023-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cnpj_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(default=1, max_length=14, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
